spring.application.name=vue3.api.ongoing
spring.datasource.url=jdbc:log4jdbc:postgresql://52.141.29.37:5555/postgres?currentSchema=ongoing
spring.datasource.username=bmmdev
spring.datasource.password=bmmdev
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.web.resources.static-locations=classpath:/static/,file:C:/upload/
spring.web.resources.static-locations=classpath:/static/images/
spring.mvc.static-path-pattern=/images/**
spring.mvc.media-types.webp=image/webp



spring.mail.host=smtp.naver.com
spring.mail.port=587
spring.mail.username=gy4171@naver.com
spring.mail.password=DWCMCU7CH6DG
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.config-location=classpath:mybatis-config.xml


server.port=8084

my.vue.base-url=http://localhost:5174